### ISSUE TITLE
Very strange result

### ISSUE THREAD

**Issue by simmed00** [divelab/GraphBP#12]
Thanks for the great work and sharing the code.

I run it according to the instruction using the provided train_epoch33 model.
I test it on one pocket, I picked a line from the train file and put into the test_selected_targets.type as below:
1 0 1.90832 1A1C_MALDO_2_433_0/1m7y_A_rec.pdb 1A1C_MALDO_2_433_0/1m7y_ppg_uff2.sdf.gz #-4.20313

 I run main_gen then main_eval.py. But main_eval will raise exception for every generated molecule by the line in bond_adder:
Chem.SanitizeMol(rd_mol,Chem.SANITIZE_ALL^Chem.SANITIZE_KEKULIZE)
So I modify it to 
Chem.SanitizeMol(rd_mol)
Then everything is smooth.

However, the results look really strange. I can post some here for your reference.
![2](https://user-images.githubusercontent.com/45054370/197126562-f3b12302-e6da-4b1d-bc38-47d3064e3670.png)
![5](https://user-images.githubusercontent.com/45054370/197126608-3113398d-5d2a-437c-96c4-1d94087c96f0.png)
![13](https://user-images.githubusercontent.com/45054370/197126662-e3e95060-bba7-4839-8002-97611cce4367.png)
![21](https://user-images.githubusercontent.com/45054370/197126685-ab508005-69b4-4f45-833b-52fdce0e1b4b.png)

Is there something I do it wrong in the step described above? Looking forward to your reply.

**Comment by mengliu1998** [comment]
Hi @simmed00,

Could you try more pockets and evaluate the results? It's worth noting that GraphBP is an early attempt for this challenging structure-based drug design problem, and there is a large space for performance improvement. Thus, the generated molecules for some pockets may not be good. Thank you.

**Comment by simmed00** [comment]
Thank you very much for the prompt reply. I was thinking could this because of the line: Chem.SanitizeMol(rd_mol,Chem.SANITIZE_ALL^Chem.SANITIZE_KEKULIZE)
Basically no molecule can pass this.
If I change to Chem.SanitizeMol(rd_mol) then basically the sanitize does nothing.
I run this on Windows 11 Anaconda, Python3.8 Pytorch 1.8, RDkit=2022.03
Normally how many molecules need to generate to get a valid one?

**Comment by mengliu1998** [comment]
Hi, could you point me to the specific line you are referring to? I have not tested the code on Windows yet. That could be the reason of using RDKit on Windows. But I am not sure.

**Comment by simmed00** [comment]
The code is around bond_adding.py line 324

try:
            # Chem.SanitizeMol(rd_mol,Chem.SANITIZE_ALL^Chem.SANITIZE_KEKULIZE)
            Chem.SanitizeMol(rd_mol,Chem.SANITIZE_ALL)
            print('Success')
        except:
            print('ReconsError')
            # raise MolReconsError()
If I use the original code, it will raise exception for every molecule generated.

Thanks in advance.

**Comment by mengliu1998** [comment]
I haven't meet this before on Linux. Will take a deeper look.

**Comment by simmed00** [comment]
I tried it on Linux, the exception is now gone without modifying your code. So the previous error is possibly due to RDKit compatibility on windows.
However, the result still looks quite weird for the generated molecules, though I haven't tested the docking score.

**Comment by mengliu1998** [comment]
Sounds great. That's a good catch!
We also found that our generated molecules are far from drug-like. We are currently working on improving the performance. Thank you and let me know if you have any further discussions or questions.
