### ISSUE TITLE
The initial ligand

### ISSUE THREAD

**Issue by 1121091694** [divelab/GraphBP#13]
Nice Paper，could you tell me how to add the atom and atomic coordinate of the initial ligand in the sample of protein pocket? Just like smiles seq2seq, we give the prompt of sequence like CCCC. In this work, we give the initial ligand like atom and xyz.

**Comment by mengliu1998** [comment]
Hi, thanks for the interest. GraphBP is tackling the problem of generating 3D molecules from scratch with given protein pocket. Are you referring to the setting where you have the smiles of the ligand and would like to predict the docking between the ligand and the protein pocket?
