### ISSUE TITLE
Results Problem

### ISSUE THREAD

**Issue by ZJoYuan** [divelab/GraphBP#14]
Hello! I use main_gen.py to generate ligands for the data in [https://github.com/pengxingang/Pocket2Mol/blob/main/data/test_list.tsv], which is also in the crossdocked2020 dataset, but lots of the ligands I generate are not in the protein pocket. (Figure 1 shows the structure of protein pocket with the reference ligand, and Figure 2 shows the structure of protein pocket with the generated ligands) Are these results correct?
<img width="500" alt="1" src="https://user-images.githubusercontent.com/75797624/231454985-a07c2cc6-03c9-40a5-92e7-46b981c7d080.png">
<img width="275" alt="2" src="https://user-images.githubusercontent.com/75797624/231454989-a8a21fc2-c20e-43dc-9aa0-9aee414536a1.png">

**Comment by mengliu1998** [comment]
Hi @ZJoYuan, this could happen. During generation, we [set the binding site range as 15A around the reference ligand](https://github.com/divelab/GraphBP/blob/332d7907f0e610bfa9cb3f4af7503c92d1814850/GraphBP/runner.py#L162). So molecules might be generated around such an area.
