### ISSUE TITLE
Code for evaluation

### ISSUE THREAD

**Issue by zaixizhang** [divelab/GraphBP#6]
Hi, thanks for the awesome work.
I did not find the code to evaluate the generated molecules, e.g., the code to compute the affinity.
Would you kindly provide this part of code?

**Comment by mengliu1998** [comment]
Hi @zaixizhang, thanks for your interest. We include the simple evaluation code on Colab: https://colab.research.google.com/drive/1Ka0p-3N4NVDGn50YGvQlDV8-Ab2d01DT?usp=sharing. Hope this helps.
