### ISSUE TITLE
Data preparation BUG

### ISSUE THREAD

**Issue by JackAILab** [divelab/GraphBP#9]
#<img width="1392" alt="image" src="https://user-images.githubusercontent.com/112920087/193730884-5ddb4416-50c7-43e3-a2be-c89fc3cac594.png">

Dear Authors, when we run your code "python scripts/split_sdf.py data/crossdock2020/it2_tt_0_lowrmsd_mols_train0_fixed.types data/crossdock2020", we have downloaded and replaced the old train0_fixed.types file, but we also got one BUG as shown in the screen shoot.
How can I solve this? Ask for help, thank you a lot!

**Comment by mengliu1998** [comment]
Hi @JackAILab,

Thanks for the interest. This looks to be an rdkit error. Are you using the same rdkit version?

**Comment by JackAILab** [comment]
> 

<img width="692" alt="image" src="https://user-images.githubusercontent.com/112920087/194029386-0f5e2975-f16c-46b6-afa1-6dca8fe7b5c9.png">
Yes, I have installed rdkit==2022.3.5， the detailed log of this bug is shown as follows:
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/112920087/194029799-65f8d272-086b-42f6-a80a-0faa2a9863a0.png">

### Should I uninstall the rdkit or use other packge? Thank you for your replying~

**Comment by JackAILab** [comment]
By the way, when I run _"python scripts/split_sdf.py data/crossdock2020/it2_tt_0_lowrmsd_mols_test0_fixed.types data/crossdock2020"_ \,  all data can be split right.

**Comment by JackAILab** [comment]
I have solved this proble by change my rdkit package, than you for your helping~
